### ISSUE TITLE
Program not writing password

### ISSUE THREAD

**Issue by YC-Chow** [thearyadev/MSRF#1]
At the enter password page, the logs says writing password but the password not entered at all. I have checked that the password given is correct. I have noticed that it immediately stops after the writing passord log appears
![Capture](https://user-images.githubusercontent.com/73323769/211184747-07b953c3-f5ff-4384-8b5d-347a8eb5c228.JPG)

**Comment by thearyadev** [comment]
Hello. Are there any errors in the log window? The log window errors would include [WARNING], [ERROR], [CRITICAL] if they show up.

You could also try entering your password manually, and seeing if the farmer continues running.

I’m currently working on two things that will make problems easier to debug: 

1. An error reporter which creates a full error report of: current browser state, account data from rewards.bing.com, the browser HTML source at the time of the error, and a screenshot of the browser at the time of the error. 
2. Removing account information from log window, so they can be shared here, without including your emails/passwords.


Without more information it’s hard to replicate. If it’s a common login problem i will likely find it in my testing.

**Comment by YC-Chow** [comment]
There isn't any errors, the farmer stops after writing password. I tried entering the password manually too but doesn't work
