### ISSUE TITLE
Please Add Auto Farming 

### ISSUE THREAD

**Issue by TESTYEE-09** [thearyadev/MSRF#12]
Please add a button to run it every day at a specified time.

**Comment by thearyadev** [comment]
Hello. I will look into making this an easily accessible option. 

Currently, it runs after 27 hours has passed on a single account. If you click the folder icon in the toolbar, you can then open the file `configuration.yaml`. This file includes a line `minimum_auto_rerun_delay_seconds` which is the number of seconds to wait before considering an account eligible to be re-run.

If you were to set this to 24 hours, then run it at 2PM, it would run every day at 2PM.
