### ISSUE TITLE
Minimize Button

### ISSUE THREAD

**Issue by inverspe** [thearyadev/MSRF#13]
Add a minimize button beside the X button

**Comment by thearyadev** [comment]
WIll be included in v0.6b.

**Comment by thearyadev** [comment]
v0.6b now includes a minimize button. 
The way window buttons are currently handeled is by using an icon button, which sometimes has problems with certain icons. 
The default minimize icon doesn't work correctly so ive replaced it with the next best thing. It looks kind of weird but it works.

Once theres a fix in the ui library im using, ill make the change to a normal looking minimize button. 


[minimize button commit](https://github.com/thearyadev/MSRF/commit/c2adb3ad07947b40459e694bb8958459931e9c2e)
