### ISSUE TITLE
[FEATURE] Proxy Support 

### ISSUE THREAD

**Issue by TatsP** [thearyadev/MSRF#15]
Please add Proxy Support as using multiple accounts without it is extremely difficult, it will not be difficult to include proxy support so please provide an option to add one proxy per account in the database which would be used for the particular account. The others bots already have this option and it would only require a flag to the chrome driver and to add the proxies in the database for each account.

**Comment by thearyadev** [comment]
This is not something i am looking to implement anytime soon. 
I'd reccomend just using a VPN to avoid IP bans.

**Comment by TatsP** [comment]
> This is not something i am looking to implement anytime soon. I'd reccomend just using a VPN to avoid IP bans.

Using multiple accounts causes issues with VPN, a proxy per account helps in preventing account bans, many other bots support proxy per account so if that can be added it will be of great help.
