### ISSUE TITLE
Some additional feature suggestions

### ISSUE THREAD

**Issue by TatsP** [thearyadev/MSRF#2]
Please add support for proxy per account, also add other earning tasks such as MSN Fitness videos, Microsoft Edge News and MSN Shopping Quiz, this will result in earning almost 200 more points per account daily.

**Comment by thearyadev** [comment]
Proxy support is on the list of things id like to implement soon. Proxy support would be up to the user to find and use suitable proxy servers, and ensure those proxy servers are the same geographic location as the account(s) they are used on. 

So far I havent had any bans on the 5 accounts I've used for testing, over 33 days. no proxy servers. I'll look into how necessary it is though. 

Other methods of getting points is also on my todo list. I dont have an ETA for this though, as my current focus is to make this project maintainable.

Thank you for the suggesttions!
