### ISSUE TITLE
[FEATURE] Concurrent Execution & Point Collection History

### ISSUE THREAD

**Issue by namimama** [thearyadev/MSRF#20]
I would like to suggest an option to remove accounts, also put how many points he had when he logged in and how many are left after he did all the tasks, a progress of what is being done, and perhaps an option for how many accounts run simultaneously

**Comment by thearyadev** [comment]
Hello. Thank you for the feedback. 

> Removing Accounts

Removing accounts is already there, long-pressing on the account name will open a dialog asking if you would like to delete the account. 

> Point Progress

This is already in the logic of the program, i record every run into the database `accounts.sqlite`. I’d like to add this information to the GUI but I’ve had a difficult time trying to make it fit without overcrowding. In my v0.7b development build, I’m already working on adding some information to the accounts table, which makes it even more difficult to add this specifically. 

I plan to move away from a data table to display accounts, it simply takes up too much space for the amount of data it can hold. When i make this change, i will also include the point progress of the previous run for each account

> Simultaneous Account Execution

I currently do not know if there is a major risk of getting banned by Microsoft for multiple accounts running on the same IP address at the Same time. 

That being said, this idea has come across my mind in case there are people that want it. The current method of running accounts doesn’t fully support multiple accounts running consecutively. 

I’m going to be moving to a “Queue” based system, where multiple workers (running on different threads) can access a “Job” from the queue, and do that job. The job would be: Farm points, refresh point count, etc. 

I will share ETA’s on these things once they are near ready.

**Comment by namimama** [comment]
I understand, thank you very much, I look forward to it.
