### ISSUE TITLE
Daily Quests not working and incomplete searches

### ISSUE THREAD

**Issue by KaitoYizon** [thearyadev/MSRF#21]
The daily quest cards are not working, just the second card seems to be completed, and the phone searches usually are incomplete, i tried running the program two or three times but it is still not getting more searches.

Im Spanish so sorry for my english.

**Comment by thearyadev** [comment]
HI. Please share any error logs. They will be in the `./errors` folder where the executable file is located. (Click the folder icon in the app)

I’m not currently aware of any problems for the daily set, in my testing the daily set is successful almost 100% of the time. I don’t have easy access to multi-region testing currently, which could be the source of the problem. 

What region are you in? 
Are you using a VPN while farming points?
What errors does the log window display?

**Comment by KaitoYizon** [comment]
I am from Spain, so I guess that is the region
I am not using a VPN
I'm not always looking at the log screen but usually says:
- Unknown error trying to complete single bing search,
- [Critical] [<waitUntilVisible>] [line 25],
- [Error] [<verify_bing_login>] [Line 37],


Those are the ones I usually see.








[error_pulumbusa@gmail.com_1675474738.543606.zip](https://github.com/thearyadev/MSRF/files/10601501/error_pulumbusa%40gmail.com_1675474738.543606.zip)
[error_pulumbusa@gmail.com_1675003059.46665.zip](https://github.com/thearyadev/MSRF/files/10601506/error_pulumbusa%40gmail.com_1675003059.46665.zip)
[error_pulumbusa@gmail.com_1675081674.91328.zip](https://github.com/thearyadev/MSRF/files/10601513/error_pulumbusa%40gmail.com_1675081674.91328.zip)
[error_pulumbusa@gmail.com_1675132693.623958.zip](https://github.com/thearyadev/MSRF/files/10601520/error_pulumbusa%40gmail.com_1675132693.623958.zip)
[error_pulumbusa@gmail.com_1675211758.087432.zip](https://github.com/thearyadev/MSRF/files/10601533/error_pulumbusa%40gmail.com_1675211758.087432.zip)
[error_pulumbusa@gmail.com_1675302224.16623.zip](https://github.com/thearyadev/MSRF/files/10601555/error_pulumbusa%40gmail.com_1675302224.16623.zip)
[error_pulumbusa@gmail.com_1675382359.314817.zip](https://github.com/thearyadev/MSRF/files/10601587/error_pulumbusa%40gmail.com_1675382359.314817.zip)

Thanks.

**Comment by ZENG61** [comment]
I also encountered this problem. I am from China and use a VPN from the United States. How to solve this problem?

**Comment by ZENG61** [comment]
I also encountered this problem. I am from China and use a VPN from the United States. How to solve this problem?

**Comment by thearyadev** [comment]
I’m currently looking into multiple region support. It’s a bit of an issue right now because of different types of content (or account language settings) that could cause problems. 

In my testing, the accounts i create/earn points on with a VPN get banned within a few hours, completely suspended from MS rewards, making this fairly difficult to test. 

I don’t have an ETA on this, and im not sure if full support for multiple account regions/running regions is possible for me. I will post updates here. Thanks for the error reports @KaitoYizon
