### ISSUE TITLE
The Bot Ins't Working

### ISSUE THREAD

**Issue by namimama** [thearyadev/MSRF#22]
When I try to open it after a few seconds I get this message 

![image](https://user-images.githubusercontent.com/105251704/218095759-6171f6bc-6cda-428b-89b1-9c4a029d1c0d.png)

**Comment by DerMuffin** [comment]
Which python version you use? @namimama

**Comment by thearyadev** [comment]
@DerMuffin  This exception handling is done from Pyinstaller, the library used to package MSRF to an executable. That being said, the python installation is automatically configured to be the same as my development environment. 

I'm not entirely sure why this is happening. It could be the port used by Flet is already occupied. Ill make a change to prevent this for the next beta version. Can't provide an ETA for this yet.
