### ISSUE TITLE
Found a Bug, how to fix?

### ISSUE THREAD

**Issue by anti-depressants** [thearyadev/MSRF#25]
I noticed that when I run an account the script gets stuck when searching the webite when a cookies popup comes up and stops it from being able to do the quiz, and therefore just skips a whole lot. What I've done is gone into debugging mode and then whilst its running I accept the cookies quickly whilst the script is on. This does fix the issue and allows the script to work, and when I do this I do not receive any sort of error in the errors folder.

Is it possible for me to modify the code so I can make it automatically accept the cookies popup? Whenever I reopen the program the cookies seem to reset so I need to redo the whole process.

**Comment by thearyadev** [comment]
Hello. Sorry for the late response. I've taken a small break from this project to complete some school work. Ill be back soon to help with this. 

(I'm also currently investigating this problem. When i have an answer i will get back to you)
