### ISSUE TITLE
[BUG] More Error messages (most likely region related)

### ISSUE THREAD

**Issue by v1rtu0s** [thearyadev/MSRF#26]
First of all thanks for this amazing project!

As I saw in a different thread, you requested error messages (most likely due to different regions/the website differently structured etc.) from people, so I gladly oblige.

The dashboard json data is also included. Region is germany.

[dashboard.txt](https://github.com/thearyadev/MSRF/files/10774071/dashboard.txt)
[error_konrad.neumann1@gmail.com_1676719767.038097.zip](https://github.com/thearyadev/MSRF/files/10774072/error_konrad.neumann1%40gmail.com_1676719767.038097.zip)

**Comment by thearyadev** [comment]
Hello. Sorry for the late response. I've taken a small break from this project to complete some school work. Ill be back soon to help with this.
