### ISSUE TITLE
Microsoft Defender Antivirus reports a trojan in msrf.exe : Sabsik.EN.D!ml

### ISSUE THREAD

**Issue by quadbyte** [thearyadev/MSRF#27]
**Describe the bug**
With the latest virus definition installed, Microsoft Defender Antivirus reports a trojan in msrf.exe : Sabsik.EN.D!ml

**Expected behavior**
No virus reported.

**Version Number**
0.7b

**Comment by thearyadev** [comment]
Thanks. I was made aware of this a few days ago when helping my friend install the new version. 

I wasn't able to replicate the behavior on my development system, although i do have an idea of why this is happening. 

In the past, PyInstaller (the library used to package this into an executable) gets tagged as malware by the operating system. 
[example stackoverflow post](https://stackoverflow.com/questions/64788656/exe-file-made-with-pyinstaller-being-reported-as-a-virus-threat-by-windows-defen)
[example stackoverflow post #2](https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg)

I recently updated the dependency version for PyInstaller, which may have had major changes that i wasnt fully aware of. That is likely the cause of the problem. 

I'm working on addressing this. Will provide updates here. 
You should be safe to bypass the warnings from your antivirus for now.

**Comment by thearyadev** [comment]
This should no longer be an issue.
