### ISSUE TITLE
[BUG] passwords are output in plain text in the webui logs

### ISSUE THREAD

**Issue by mgrimace** [thearyadev/MSRF#29]
**Describe the bug**
Passwords are occasional output in plaintext in the webui logs, which would technically be viewable by anyone connected to the local network (minimal risk as they'd need the IP and Port, but still not ideal).

Sample:

![screenshot](https://github.com/thearyadev/MSRF/assets/55518507/1686cbed-1fc2-41d2-ac70-85ae03223669)

**Expected behavior**
Ideally, passwords would not be shown in the webui logs

**Version Number**
0.8 b - docker/server deployment

**Error Report**
Not an error per se, more of a minor security issue/preference.

**Comment by thearyadev** [comment]
I previously had them hidden, but revealed them during testing when i had an issue with password submissions in the GUI. 

will hide them in the next version. 

Thanks.
