### ISSUE TITLE
very good alternative however...

### ISSUE THREAD

**Issue by inverspe** [thearyadev/MSRF#5]
it needs to open chrome to start farming points unlike the original one which doesn't need to 

apart from that I have one suggestion is to hide the python prompt once the actual ui has loaded

It's great overall does the job done and nice UI

**Comment by thearyadev** [comment]
It shouldn't need to open the chrome window. May be a bug with the v0.3b release, so i will look into it.

**Comment by inverspe** [comment]
okay, sorry I didn't download the latest version
