### ISSUE TITLE
[BUG] Incomplete PC/Mobile searches

### ISSUE THREAD

**Issue by inverspe** [thearyadev/MSRF#6]
There are times that it only searches few for mobile searches and just moves on the other account just like the original counterpart you should look into it otherwise that's the only problem I have encountered so far

**Comment by thearyadev** [comment]
Hello. 

Thank you for the feedback. I will look into it.

Its likely a common bug, I'm still working on addressing it.

**Comment by namimama** [comment]
This is because in some regions the order of searches is different, e.g. in some countries the computer search will start first, then the edge and then the mobile.
